### ISSUE TITLE
Cache descriptions of structs to avoid repeated reparsing of tags

### ISSUE THREAD

**Issue by alex** [ianlopshire/go-fixedwidth#15]
In a benchmark I have of repeatedly calling `Decode(&myStruct)`, nearly 20% of the time is being spent parsing tags.

The stdlib json package caches a description computed description of structs it receives in order to avoid this sort of overhead.

**Comment by alex** [comment]
Relevant piece of the code: https://github.com/golang/go/blob/145e193131eb486077b66009beb051aba07c52a5/src/encoding/json/encode.go#L1271-L1280

**Comment by ianlopshire** [comment]
`Encoder` already does this. I think implementing it in the decoder would be a straight forward change. I can jump on this if you don't have any plans to.

**Comment by alex** [comment]
Hah! I filed this thinking it would be a non-trivial amount of work, but seeing that I can just reuse the encode-side logic, I whipped up a patch.

**Comment by ianlopshire** [comment]
@alex, just cut release `v0.4.1` that includes the change. Thanks for adding this!

**Comment by alex** [comment]
@ianlopshire Sorry, just noticed the opportunity for further optimization in #17!

**Comment by ianlopshire** [comment]
@alex, nice catch! I merged the the PR and cut release `v0.4.2`.

**Comment by alex** [comment]
@ianlopshire thanks for being so responsive on these!
