### ISSUE TITLE
Add formatting options (e.g. left pad)

### ISSUE THREAD

**Issue by ianlopshire** [ianlopshire/go-fixedwidth#28]
The encoder should support common formatting needs such as left padding.

### Formatting Options

* `default` - No padding is applied to the value.
* `rightpad` - The value is padded on the right to fill available space.
* `leftpad` - The value is padded on the left to fill available space.

In all cases the value is written to the available space in a left-to-right manner. If the value length is greater than available space, the right most characters will be omitted.

### Struct Tags

The struct tag schema will be updated to support and optional third option to specify formatting – `fixed:"{startPos},{endPos},{format}"`.

### Padding Characters

| Types | Padding Character |
| ----- | ------------------- |
| `int`, `int8`, `int16`, `int32`, `int64` | `0` |
| `uint`, `uint8`, `uint16`, `uint32`, `uint64` | `0` |
| `float32`, `float64`| `0` |
| `string`, `[]byte` | `\u0020` (space)  |

Any type not listed will default to being padded with `\u0020` (space).

**Comment by ianlopshire** [comment]
It would also be advantageous to allow the user to define the character that will be used for padding. 

This would change the struct tag schema to `fixed:"{startPos},{endPos},{format},{padChar}"`. Both new parameters would be optional. If `padChar` is not defined it should fall back to the table defined above.

The only issue I see with this is defining space as the padding character. Using a literal space is har to read (e.g. `fixed:"1,5,rightpad, "`). I propose `_` is used for space and `__` is used for a literal underscore.

With this in place, it would be trivial to implement a `right` and `left` option that only control alignment. `fixed:"1,5,right"` would be an alias for `fixed:"1,5,padleft,_"`. Similarly `fixed:"1,5,left"` would be an alias for  `fixed:"1,5,padright,_"`

**Comment by coip** [comment]
> It would also be advantageous to allow the user to define the character that will be used for padding.

tuning into this thread as well.

**Comment by wallaceicy06** [comment]
👍
