### ISSUE TITLE
feature request: Allow for specifying the lengths of the fields instead of start and end

### ISSUE THREAD

**Issue by timuckun** [ianlopshire/go-fixedwidth#43]
It's much more convinient to be able to say fieldA:3 fieldB:4 etc than to calculate the start and end for all the fields.

I realize this means you have to put them in order but that's what most people will do anywya.

**Comment by ianlopshire** [comment]
I don't have any plans to implement this feature request, but [huydang284/fixedwidth](https://github.com/huydang284/fixedwidth) is an alternate package that functions this way.
