### ISSUE TITLE
No way to tell if at EOF when using Decoder.Decode() with struct

### ISSUE THREAD

**Issue by alex** [ianlopshire/go-fixedwidth#6]
Looking at:

https://github.com/ianlopshire/go-fixedwidth/blob/master/decode.go#L81-L93

and

https://github.com/ianlopshire/go-fixedwidth/blob/master/decode.go#L113-L128

As far as I can tell, `readLine` eats the EOF error -- it returns an `ok` bool, but `Decode` throws that away. This could be fixed by having `Decode` transform the `ok` bool back into an `err == io.EOF`, or the `done` bool could be exposed via a public API.

I'm happy to implement a PR for either one of these strategies that you prefer.

Thanks for this package!

**Comment by ianlopshire** [comment]
@alex, thanks for submitting this issue.

I think the best solution here, is for `Decode` to return an `io.EOF` error when there are no remaining lines to read *and* the target is not a slice. I'd prefer not to expose done and expand the public API. Decoding an empty file into a slice should result in an empty slice.

I am open to discussion if you have other thoughts.

I'd happily merge a PR for this provided it includes tests and documentation.

**Comment by alex** [comment]
Expect a PR later today! Thanks much!
