### ISSUE TITLE
Support for codepoint-based fixedwidth files

### ISSUE THREAD

**Issue by alex** [ianlopshire/go-fixedwidth#9]
I have an extremely bonkers fixed-width file format where the file is utf-8 encoded, but the fixed offsets are expressed in decoded _codepoints_. Naturally this doesn't play super well with go-fixedwidth's (ENTIRELY REASONABLE) byte-based approach :-)

I'd like to find some way to shoe-horn this into go-fixedwidth (and obviously contribute this upstream).

I think the most efficient implementation is probably, if you're doing this codepoint mode, to conver the line to `[]rune` in `readLine` and in `rawValueFromLine` convert it back to a `[]byte` with the utf-8 value.

And I think that'd all work fine. But I don't see an obvious way to do this without throwing a bunch of `if` statements here and changing a bunch of types (e.g. I could replace all the `[]byte` with `struct { bytes []byte; runes []rune }` and then sticks `if` in `readLine` and `rawValueFromLine`).

Do you have an opinion on if there's a better implementation strategy? Would I be better off just forking `decode.go`?

**Comment by ianlopshire** [comment]
Hey @alex,

I think adding codepoint based encode/decoding is worthwhile. I'd be interested in seeing the performance hit converting the entire library to use `[]rune` internally. If the performance hit isn't too bad, I think using the `[]rune` based approach could be backward compatible.

I don't like the idea of adding `struct { bytes []byte; runes []rune }` and adding `if` statements. If the performance hit for converting to `[]rune` is too great, I'd rather just maintain separate `[]byte` and `[]rune` based encoder/decoders.

**Comment by alex** [comment]
I came up with a slightly cleverer implementation! Rather than describe it I'll have a PR up shortly :-)

**Comment by alex** [comment]
@ianlopshire it looks like the 0.3 tag is at the commit before this was merged, was that intentional?

**Comment by alex** [comment]
Sorry that was a really dumb question, I just noticed that that tag is a month old.

**Comment by ianlopshire** [comment]
@alex I just cut a [v0.4.0 release](https://github.com/ianlopshire/go-fixedwidth/releases/tag/v0.4.0).

**Comment by alex** [comment]
Cool! Thanks!
